services:
  hotel-pg:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hotel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  hotel-redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  postgres_data: